image: Ubuntu2004  # образ для сборки

stack: jdk 17  # версия JDK

branches:
  only:
    - main  # ветка git

build: off  # будем использовать свой скрипт сборки

build_script:
  - ./gradlew test --info  # запускаем тест, флаг --info позволяет выводить больше информации